#!/bin/bash

echo "
	NOTE: Is recomanded to run the commands step by step!
"

while true; do
    read -p "Are you a sudoer?[Y/n]: " yn
    case $yn in
        [Yy]* ) echo "Ok. Let's proceed to password."; break;;
        [Nn]* ) echo "It's not possible to run this script. Try running commands from this script on your own."; exit;;
        * ) echo "Please answer Y(Yes) or n(no).";;
    esac
done

sudo apt update

sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo apt update
sudo apt install -y neovim

sudo apt install -y build-essential cmake curl exuberant-ctags git
sudo apt install -y python-dev python3-dev
sudo apt install -y python-dev python-pip python3-dev python3-pip xclip

# Autocomplete dependencies
sudo apt install -y clang
## ! Need to install ghc-mod ! ##
## ! Need to install racer(cargo install racer) ! ##
pip3 install jedi

sudo pip3 install --upgrade neovim

#### Install the fonts ####
echo "
-- Creating ~/.fonts folder if not exits
"
if [ ! -d ~/.fonts ]; then
    mkdir ~/.fonts
fi
echo "
-- Coping all the fonts
"
sudo cp -f ~/.hc-nvim/fonts/* ~/.fonts/
echo "
-- Making the OS aware of the new fonts
"
sudo fc-cache -f

# Install nodejs + npm
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt install -y nodejs

#### Linters ####

# Javascript
sudo npm install -g babel-eslint

# Python
sudo apt install -y pylint

#### Code formatters ####

# JS/HTML/CSS/JSON
sudo npm install -g js-beautify

# Typescript
sudo npm install -g typescript typescript-formatter

# C/C++/Objective C
sudo apt install -y clang-format
